config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  get '/flights', to: 'flights#index'

  resources :bookings, only: %i[new create show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: 'departure_id', class_name: 'Flight'
  has_many :arriving_flights, foreign_key: 'destination_id', class_name: 'Flight' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  scope :flight_from, ->(id) { where('departure_id = ?', id) }
  scope :flight_to, ->(id) { where('destination_id = ?', id) }
  scope :on_date, ->(date) { where(start_time: date.to_date.beginning_of_day..date.to_date.end_of_day) }

  belongs_to :departure, class_name: 'Airport'
  belongs_to :destination, class_name: 'Airport'
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build
    params[:num_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all.order(:start_time)
    @flight_dates = @flights.pluck('flights.start_time')
    @flight_dates = @flight_dates.map { |date| [format_flight_date(date)] }.uniq

    @airports = Airport.all.map { |airport| [airport.airport_code, airport.id] }

    unless request.query_string.empty?
      @flight_results = @flights.flight_from(params[:departing_id]).flight_to(params[:destination_id]).on_date(params[:start_time])
    end
  end

  private

  def format_flight_date(date)
    date.strftime('%d/%m/%Y')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h3>Flight Details</h3>
<div class="content-card flex-center">
  <%= render 'shared/flight_details', :flight => @booking.flight %>
</div>

<h3>Passenger Details</h3>
<% if @booking.errors.any? %>
  <div class="centered-column">
    <p>Unable to submit form due to following error(s):</p>
    <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </div>
  </ul>
<% end %>
  <%= form_with model: @booking, class: "centered-column" do |f| %>
    <%= f.hidden_field :flight_id %>
      <% i = 1 %>
    <%= f.fields_for :passengers do |passenger_form| %>
        <div class="passenger-form">
          <h4>Passenger #<%= i %></h4>
          <div class="field">
            <%= passenger_form.label :name %><br>
            <%= passenger_form.text_field :name %>
          </div>
          <div class="field">
            <%= passenger_form.label :email %><br>
            <%= passenger_form.email_field :email %>
          </div>
        </div>
        <% i += 1 %>
    <% end %>
    <%= f.submit "Submit", class: "button action" %>
  <% end %>

app/views/bookings/show.html.erb
<h2>✨ Congratulations! Your booking is complete! ✨</h2>
<h3>Flight details</h3>
<div class="content-card flex-center">
  <%= render 'shared/flight_details', :flight => @booking.flight %>
</div>
<h3>Passenger details</h3>
<div class="centered-column">
  <% i = 1 %>
  <% @booking.passengers.each do |passenger| %>
    <div class="passenger-details">
      <h4>Passenger <%= i %></h4>
      <p><%= passenger.name %></p>
      <p><%= passenger.email %></p>
    </div>
    <% i += 1 %>
  <% end %>
</div>

app/views/flights/_search_form.html.erb
<%= form_with url: '/flights', method: 'get', data: { turbo: false }, class: "search-bar" do %>
  <div class="search-field">
    <%= label_tag :departing_id, "Departing from: " %>
    <%= select_tag(:departing_id, options_for_select(airports, params[:departing_id])) %>
  </div>
  <div class="search-field">
    <%= label_tag :destination_id, "Flying to: " %>
    <%= select_tag(:destination_id, options_for_select(airports, params[:destination_id])) %>
  </div>
  <div class="search-field">
    <%= label_tag :num_passengers, "Number of passengers: " %>
    <%= select_tag(:num_passengers, options_for_select((1..4), params[:num_passengers])) %>
  </div>
  <div class="search-field">
    <%= label_tag :start_time, "Leaving on: " %>
    <%= select_tag(:start_time, options_for_select(flight_dates, params[:start_time])) %>
  </div>
  <%= submit_tag('Search') %>
<% end %>

app/views/flights/index.html.erb
<%= render "search_form", :airports => @airports, :flight_dates => @flight_dates %>

<% unless @flight_results.nil? %>
    <% if @flight_results.empty? %>
      <p>No Results Found.</p>
    <% else %>
      <%= form_with url: new_booking_path, method: 'get', data: { turbo: false }, class: 'centered-column' do %>
        <%= hidden_field_tag 'num_passengers', value = params[:num_passengers] %>
        <% @flight_results.each do |flight| %>
          <div class="content-card flex-center">
          <%= label_tag "flight_id_#{flight.id}" do %>
              <%= render 'shared/flight_details', :flight => flight %>
            <% end %>
            <div class="flight-select">
              <%= radio_button_tag :flight_id, flight.id, required: true %>
            </div>
          </div>
        <% end %>
        <%= submit_tag('Start flying!', class: 'button action') %>
      <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1 class = "header"><%= link_to "✈️ Flight Booker ✈️", root_url %></h1>
    <%= yield %>
  </body>
</html>

app/views/shared/_flight_details.html.erb
<div class="flight-details">
  <p><strong><%= flight.departure.airport_code %></strong></p>
  <%= image_tag('right-arrow-purple.png', class: 'image') %>
  <p><strong><%= flight.destination.airport_code %></strong></p>
  <p><%= flight.start_time %></p>
  <p><%= flight.duration %> hours</p>
  <p><%= flight.start_time + flight.duration.hours %></p>
</div>